# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy service

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B compile assembly:single --file pom.xml -P service -Dswear.jarSuffix=service
    - uses: actions/upload-artifact@v2
      with:
        name: target
        path: target/
    - run: mv target/*.jar git-swears
    - uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "git-swears"
        target: "/usr/bin"
        overwrite: true
        debug: true
