# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        profiles: ["cli", "service", "service,cli"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      with:
        profiles: ${{ matrix.profiles }}
      run: mvn -B compile assembly:single --file pom.xml -P ${profiles}
    - uses: actions/upload-artifact@v2
      with:
        name: target
        path: target/
